### ISSUE TITLE
backend - permitir a atualização do estado

### ISSUE THREAD

**Issue by hartmannjean** [RoutinelyOrganization/routinely-api#67]
Alterar a tarefa para permitir a edição parcial dos campos.

**Comment by viniciuscosmome** [comment]
Atualizado de `bug` para `feature` porque o recurso que estava faltando já está criado, o que está faltando é o recurso de _**atualização de tarefa**_.

**Comment by viniciuscosmome** [comment]
- marcar o card como concluído
- possibilidade de enviar apenas as propriedades que serão realmente alteradas
- corrigir o fuso horário para 'ptBR'
- o campo de data e hora serem mesclados em um único campo

**Comment by viniciuscosmome** [comment]
## Propriedades

```yml
name:
  type: string
  details: Guarda o nome da tarefa
description:
  type: string
  details: Guarda a descrição da tarefa
date:
  type: string
  pattern: YYYY-MM-DD HH:MM
  details: Guarda data e hora da tarefa
checked:
  type: boolean
tag:
  type: string
  options:
    - application
    - account
    - exercise
    - beauty
    - literature
priority:
  type: string
  options:
    - low
    - medium
    - high
    - urgent
category:
  type: string
  options:
    - personal
    - study
    - finance
    - career
    - health
```

**Comment by viniciuscosmome** [comment]
### Adicionar uma tarefa

```yml
Path: /tasks
Method: POST
Headers:
  Content-Type: application/json
  Authorization: Bearer ACCESS_TOKEN
Body:
  name: required
  description: required
  date: required
  tag: required
  priority: required
  category: required
```

### Resposta caso sucesso
```json
{
  "message": "Tarefa criada com sucesso!"
}
```

**Comment by viniciuscosmome** [comment]
### Pegar todas as tarefas do mês e ano informados

```yml
Path: /tasks
Method: GET
Headers:
  Authorization: Bearer ACCESS_TOKEN
QueryParams:
  month: required
  year: required
```

```txt
Exemplo de url:
/tasks?month=1&year=2024
```

### Resposta caso sucesso
```json
{
  "count": 7,
  "tasks": [
    {
      "id": 8,
      "name": "Nome desta tarefa",
      "description": "Descrição da tarefa",
      "date": "2024-03-12T13:00:00.000Z",
      "tag": "exercise",
      "category": "study",
      "priority": "urgent",
      "checked": false
    },
    {
      "id": 3,
      "name": "Nome desta tarefa",
      "description": "Descrição da tarefa",
      "date": "2024-03-12T13:00:00.000Z",
      "tag": "exercise",
      "category": "study",
      "priority": "medium",
      "checked": false
    },
    ...,
  ]
}
```

**Comment by viniciuscosmome** [comment]
### Pegar a tarefa com o ID informado

```yml
Path: /tasks/:id
Method: GET
Headers:
  Authorization: Bearer ACCESS_TOKEN
UrlParam:
  id: required
```

```txt
Exemplo de url:
/tasks/33
```

### Resposta caso sucesso
```json
{
  "task": {
    "id": 2,
    "name": "Nome desta tarefa",
    "description": "Descrição da tarefa",
    "date": "2024-03-12T18:42:00.000Z",
    "tag": "exercise",
    "priority": "medium",
    "category": "study",
    "checked": false
  }
}
```

**Comment by viniciuscosmome** [comment]
### Editar uma tarefa

É obrigatório editar ao menos um campo!

```yml
Path: /tasks
Method: PATCH
Headers:
  Content-Type: application/json
  Authorization: Bearer ACCESS_TOKEN
Body:
  id: required
  name: optional
  description: optional
  date: optional
  tag: optional
  priority: optional
  category: optional
  checked: optional
```

### Resposta caso sucesso
```json
{
  "updated": true
}
```

**Comment by viniciuscosmome** [comment]
### Deletar a tarefa com o ID informado

```yml
Path: /tasks/:id
Method: DELETE
Headers:
  Authorization: Bearer ACCESS_TOKEN
UrlParam:
  id: required
```

```txt
Exemplo de url:
/tasks/33
```

### Resposta caso sucesso
```json
{
  "deleted": true
}
```
